name: GitHub Actions Validator
run-name: ${{ github.actor }} esta validando este código através do github actions 🚀
on: push
jobs:
  Validando-este-repositório:
    runs-on: ubuntu-latest
    steps:
        - name: Iniciando testes
          run: echo"testes Iniciados"

        - name: Baixar código
          uses: actions/checkout@v4

        - name: instalando Node
          run: echo"Baixando Node"

        - name: Verificando Arquivos
          run: ls -n

